language: ruby
rvm:
  - 2.2
deploy:
  provider: heroku
  api_key:
    secure: "8f04df59-fa70-44a4-843c-31d2c0d57de6"
    app: projet_LPA
          master: my-app-staging
         production: my-app-production