language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: PMlZEulvZoiNo0mupClxlEQvIazbZt8T5vHQhQzKZNKfHL4jrv+WVhvnMLOrOvf8oWh+aRDH1UCNfaxhIJWdPxEXHZy/wWiLWhZdEpG+RnsFf2xphh8IdT4iiDy3ykp7YhgNYTU2xuJh/8GxngAfrCWfkJjB54h/scAX+pCT17J9t24K0KfRW2J+daSqA+JH74sQYK7+CdWQW4I8/fXhAJdSrzCz4H9Wbgeq1VwwTU6JIHJ3RKMisnIES1/I5BLn93ZkJJDcXqdK9F/joV+PHpRyFEMPKGTlJa9ly4Wbjn2a/lQNu5SatfAbN6HfOKpQqyQ2RWIPomkZVnsbTe+nE+whAuYCUglc+v7imfAOx6sUwHRy31rUkWzPoCvF64AgflO/wg+yJSMkkyyl7T6RL9Lv0d5/Zq3jb602n6qD3ij+QY+5wHlhYJqO0PxzMPxOWcft4l7jUusIbP1kAQ5naUgo48yzVGEPKrUKazCksdZKCA3lQAN4xOB/wg7YG4BADsptRZ+qEbvX3Jx4ueW9b8YTPEa8mA11CTOTylbBuEOHUzAuElYUAcNI2zhswWnrxBnsiZC76K5sZrc03RIXQ1V9Pp6gGMqzMw95HerATWKtQSMb+FDIjY+3ZryPtru/2J7WFMt6RRueb+l1teIiwVqYbhOoFGX/jzyIwv3tzqI=
  app: y
  on:
    repo: edwardAGE4/projet
